export const LOGO = "/images/hasset-logo.jpg";

export const FOOD_IMAGES = [
  "/images/food-1.jpg",
  "/images/food-2.jpg",
  "/images/food-3.jpg",
  "/images/food-4.jpg",
  "/images/food-5.jpg",
  "/images/food-6.jpg",
  "/images/food-7.jpg",
];

export const CAT_IMG: Record<string, string> = {
  breakfast: FOOD_IMAGES[2],
  traditional: FOOD_IMAGES[0],
  pasta: FOOD_IMAGES[6],
  fish: FOOD_IMAGES[3],
  beef: FOOD_IMAGES[4],
  chicken: FOOD_IMAGES[5],
  burger: FOOD_IMAGES[6],
  pizza: FOOD_IMAGES[1],
  wrap: FOOD_IMAGES[2],
  salad: FOOD_IMAGES[3],
  soup: FOOD_IMAGES[4],
  juice: FOOD_IMAGES[5],
  colddrinks: FOOD_IMAGES[6],
  hotdrinks: FOOD_IMAGES[0],
  alcohol: FOOD_IMAGES[1],
};

export interface MenuItem {
  name: string;
  desc: string;
  price: number;
}

export interface Category {
  label: string;
  icon: string;
  color: string;
  items: MenuItem[];
}

export const menuData: Record<string, Category> = {
  breakfast: {
    label: "Breakfast",
    icon: "sun",
    color: "#D97706",
    items: [
      { name: "Normal Full", desc: "Beans, onion, tomato, green pepper, egg, salt", price: 200 },
      { name: "Special Full", desc: "Beans, onion, tomato, green pepper, egg, salt", price: 230 },
      { name: "Scrambled Egg", desc: "Egg, onion, tomato, celery, salt", price: 230 },
      { name: "Egg with Meat", desc: "Egg, meat, onion, tomato, celery, salt", price: 299.99 },
      { name: "Special Nashif", desc: "Dabo firfir, egg, yogurt, onion, tomato, celery, salt", price: 220 },
      { name: "Egg with Tomato Sauce", desc: "Tomato sauce, egg, green pepper, salt", price: 249.99 },
      { name: "Fetira with Egg", desc: "Kita, egg, honey", price: 299.99 },
      { name: "Fetira with Honey", desc: "Kita with honey", price: 250 },
      { name: "Pan Cake", desc: "Flour, milk, egg, sugar, baking powder, salt, vanilla", price: 199 },
      { name: "Pancakes with Banana Cream", desc: "Flour, milk, egg, sugar oil, baking powder, salt, banana", price: 260 },
      { name: "Pancakes with Strawberry Cream", desc: "Flour, milk, egg, sugar, oil, baking powder, salt, strawberry", price: 260 },
      { name: "Banana Cake", desc: "", price: 100 },
      { name: "English Cake", desc: "", price: 100 },
      { name: "Bula Genfo", desc: "Bula flour, water, salt, butter, berbere, yoghurt", price: 250 },
      { name: "Bula Genfo with Kitfo (1 person)", desc: "", price: 420 },
      { name: "Bula Genfo with Kitfo (2 persons)", desc: "", price: 650 },
      { name: "Bula Genfo with Kitfo (3 persons)", desc: "", price: 800 },
      { name: "Qinche", desc: "", price: 250 },
      { name: "Hasset Combo", desc: "Scrambled egg, firfir, injera", price: 700 },
      { name: "Avocado Lebleb", desc: "Avocado, onion, green chilli, garlic, oil, black pepper, salt", price: 230 },
      { name: "Chechebsa Fasting", desc: "", price: 250 },
      { name: "Chechebsa with Egg", desc: "Kita firfir, honey, egg, butter", price: 280 },
      { name: "Black Tef Chechebsa", desc: "", price: 280 },
      { name: "Special Black Tef Chechebsa", desc: "", price: 330 },
      { name: "Fasting Firfir", desc: "", price: 250 },
      { name: "Tibis Firfir", desc: "Meat, red sauce or yellow, butter", price: 430 },
      { name: "Quanta Firfir", desc: "Dry meat, red sauce, egg, onion", price: 420 },
      { name: "Derkosh Firfir", desc: "Dry meat, dry injera", price: 320 },
      { name: "Cheese Omelet", desc: "Cheese, egg, onion, tomato, green pepper, salt, black pepper", price: 250 },
      { name: "Omelet", desc: "Egg, onion, tomato, green pepper, salt, black pepper", price: 206 },
      { name: "French Toast", desc: "Egg with fried bread", price: 260 },
      { name: "Duleat", desc: "Meat, onion, green pepper, local butter", price: 390 },
    ],
  },
  traditional: {
    label: "Traditional",
    icon: "utensils",
    color: "#7C3AED",
    items: [
      { name: "Shiro with Salad", desc: "", price: 280 },
      { name: "Half Half", desc: "", price: 350 },
      { name: "Special Shiro", desc: "", price: 370 },
      { name: "Fasting Special Shiro", desc: "", price: 310 },
      { name: "Shiro Tegabino with Salad", desc: "", price: 320 },
      { name: "Bozena Shiro", desc: "", price: 310 },
      { name: "Fasting Firfir", desc: "", price: 250 },
      { name: "Tuna Firfir", desc: "", price: 450 },
      { name: "Meat Firfir", desc: "", price: 430 },
      { name: "Tibs Firfir", desc: "", price: 430 },
      { name: "Quanta Firfir", desc: "", price: 450 },
      { name: "Chikina Tibs", desc: "", price: 530 },
      { name: "Lamb Tibs", desc: "", price: 570 },
      { name: "Kikil", desc: "", price: 520 },
      { name: "Beyayint", desc: "", price: 320 },
      { name: "Hasset Combo", desc: "Botheza shiro, tibs firfir, tibs, scrambled egg", price: 700 },
      { name: "Fasting Combo", desc: "Tebabino, fasting firfir, rice, vegetable, salad", price: 500 },
      { name: "Chef Combo", desc: "Fasting firfir, tibs firfir, tibs, scrambled egg", price: 800 },
      { name: "Suf Fitfit", desc: "", price: 200 },
      { name: "Normal Yoghurt", desc: "", price: 150 },
      { name: "Flavor Yoghurt", desc: "", price: 180 },
    ],
  },
  pasta: {
    label: "Pasta & Rice",
    icon: "wheat",
    color: "#B45309",
    items: [
      { name: "Spaghetti / Rice with Vegetable", desc: "Zicchini, french benis, carrot, cabbage, spinach", price: 280 },
      { name: "Spaghetti / Rice with Tomato", desc: "Tomato sauce", price: 280 },
      { name: "Spaghetti / Rice with Meat Sauce", desc: "Tomato sauce, meat, cream, cheese", price: 370 },
      { name: "Spaghetti / Rice with Tuna", desc: "Tomato sauce, meat, tuna", price: 450 },
      { name: "Spaghetti / Rice with Chicken", desc: "Chicken, cream, milk, onion, pepper, tomato", price: 400 },
      { name: "Lasagna", desc: "Meat, sauce, cream, cheese, black pepper, salt", price: 400 },
    ],
  },
  fish: {
    label: "Fish",
    icon: "fish",
    color: "#0891B2",
    items: [
      { name: "Grilled Fish", desc: "Fish fillet grilled with rice, vegetable", price: 550 },
      { name: "Fish Gulash", desc: "Fish, tomato sauce, onion, green pepper with rice", price: 550 },
      { name: "Fish Cottelet", desc: "Fish, fried egg, bread flour, served with rice", price: 550 },
      { name: "Hot & Spice Finger Fish", desc: "Hot fried fish, tomato, onion, green pepper and chips", price: 550 },
    ],
  },
  beef: {
    label: "Beef",
    icon: "beef",
    color: "#DC2626",
    items: [
      { name: "Pepper Steak", desc: "Grilled beef fillet, cream, pepper, rice", price: 530 },
      { name: "Stir Fried Beef", desc: "Beef fillet, mixed spaghetti with vegetable/rice, green pepper, tomato, onion, pepper", price: 530 },
      { name: "Beef Kebeb", desc: "Beef fillet, onion, tomato, pepper, served with rice/chips", price: 530 },
      { name: "Beef Gulash", desc: "Beef fillet, green pepper, tomato sauce, onion, pepper, rice", price: 530 },
    ],
  },
  chicken: {
    label: "Chicken",
    icon: "drumstick",
    color: "#EA580C",
    items: [
      { name: "Full Roasted Chicken", desc: "Served with rice, vegetable and salad", price: 2000 },
      { name: "Roasted Half Chicken", desc: "Served with rice, vegetable and salad", price: 1100 },
      { name: "Chicken Cottelet", desc: "Chicken, bread cramp, flour, egg, rice", price: 600 },
      { name: "Fried Chicken Leg", desc: "Fried chicken, leg, flour, bread, cramp, egg, rice", price: 550 },
      { name: "Grilled Chicken Breast", desc: "Chicken breast, served with rice and vegetable", price: 550 },
    ],
  },
  burger: {
    label: "Burgers & Sandwiches",
    icon: "sandwich",
    color: "#D97706",
    items: [
      { name: "Hasset Special Burger", desc: "Season beef, cheese, ham, egg, lettuce, tomato, onion", price: 620 },
      { name: "Double Special Burger", desc: "Double season beef, cheese, ham, egg, lettuce, tomato, onion", price: 740 },
      { name: "Double Beef Burger", desc: "Double season beef, salad, tomato, onion, pepper", price: 599.99 },
      { name: "Cheese Burger", desc: "Season beef, cheese, salad, tomato, onion, pepper", price: 499.99 },
      { name: "Normal Burger", desc: "Season beef, salad, tomato, onion, pepper", price: 430 },
      { name: "Ham Burger", desc: "Season beef, ham, tomato, onion, pepper", price: 530 },
      { name: "Club Sandwich", desc: "Beef, chicken, cheese, salad, mayonnaise, egg", price: 499.99 },
      { name: "Chicken Sandwich", desc: "Chicken, salad, mayonnaise, onion, black pepper", price: 600 },
      { name: "Tuna Sandwich", desc: "Tuna, salad, tomato, onion, pepper, salt", price: 470 },
      { name: "Egg Sandwich", desc: "Egg, onion, tomato, pepper, salt", price: 280 },
      { name: "Vegetable Sandwich", desc: "Mixed cooked vegetable", price: 280 },
      { name: "French Fries", desc: "", price: 260 },
    ],
  },
  pizza: {
    label: "Pizza",
    icon: "pizza",
    color: "#C2410C",
    items: [
      { name: "Hasset Special Pizza", desc: "Mozzarella, tomato sauce, beef, olive, mushroom, beef ham, boiled egg, oregano", price: 830 },
      { name: "Chef Special Pizza", desc: "Double surprise pizza", price: 1050 },
      { name: "Chicken Pizza", desc: "Tomato sauce, mozzarella, chicken, mushroom, oregano", price: 870 },
      { name: "Beef Pizza", desc: "Tomato sauce, beef, mozzarella, oregano", price: 730 },
      { name: "Tuna Pizza", desc: "Tomato sauce, tuna, oregano, pepper, olive", price: 650 },
      { name: "Tuna with Cheese Pizza", desc: "Tomato sauce, tuna, mozzarella, oregano, pepper, onion", price: 700 },
      { name: "Vegetable with Cheese Pizza", desc: "Tomato sauce, mozzarella, cooked vegetable", price: 600 },
      { name: "Vegetable Fasting Pizza", desc: "Tomato sauce, cooked vegetable", price: 500 },
      { name: "Margarita Pizza", desc: "Tomato sauce, mozzarella, oregano", price: 610 },
      { name: "Four Season Pizza", desc: "Tomato sauce, beef, vegetable, olive, mushroom, beef ham, oregano", price: 1090 },
      { name: "Family Special Pizza", desc: "Mozzarella, tomato sauce, beef, olive, mushroom, beef ham, boiled egg, oregano", price: 1050 },
    ],
  },
  wrap: {
    label: "Wraps",
    icon: "burrito",
    color: "#059669",
    items: [
      { name: "Vegetable Wrap", desc: "", price: 290 },
      { name: "Tuna Wrap", desc: "", price: 470 },
      { name: "Chicken Wrap", desc: "Chicken breast, onion, tomato, green pepper, mayonnaise, lettuce, cheese, soya, ketchup, chips", price: 550 },
      { name: "Beef Wrap", desc: "Beef, onion, tomato, green pepper, mayonnaise, lettuce, cheese, soya, ketchup, chips", price: 520 },
    ],
  },
  salad: {
    label: "Salads",
    icon: "salad",
    color: "#16A34A",
    items: [
      { name: "Hasset Special Salad", desc: "Chicken, beef, mayonnaise, egg, olive, grilled ham, lettuce, cucumber, tomato, onion, pepper", price: 470 },
      { name: "Tuna Salad", desc: "Lettuce, tomato, tuna, onion, pepper, cucumber dressing", price: 420 },
      { name: "Normal Salad", desc: "Lettuce, tomato, onion, pepper, cucumber", price: 250 },
      { name: "Avocado Salad", desc: "Tuna, salad, tomato, onion, pepper, salt, cucumber", price: 300 },
      { name: "Home Made Salad", desc: "Onion, tomato, green pepper, oil, hot pepper", price: 250 },
    ],
  },
  soup: {
    label: "Soups",
    icon: "soup",
    color: "#92400E",
    items: [
      { name: "Tomato Cream Soup", desc: "Served with rice, vegetable and salad", price: 200 },
      { name: "Vegetable Soup", desc: "Served with rice, vegetable and salad", price: 200 },
      { name: "Beef Soup", desc: "Beef, bread cream, flour, egg, rice", price: 250 },
      { name: "Chicken Soup", desc: "Chicken, milk, cream, butter, black pepper", price: 250 },
    ],
  },
  juice: {
    label: "Juices & Shakes",
    icon: "glass-water",
    color: "#CA8A04",
    items: [
      { name: "Avocado Juice", desc: "", price: 200 },
      { name: "Mango Juice", desc: "", price: 200 },
      { name: "Papaya Juice", desc: "", price: 170 },
      { name: "Watermelon Juice", desc: "", price: 170 },
      { name: "Flax Seed Shake", desc: "", price: 200 },
      { name: "Mixed Juice", desc: "", price: 200 },
      { name: "Fruit Punch", desc: "", price: 300 },
      { name: "Carrot Juice", desc: "", price: 200 },
      { name: "Banana Shake", desc: "", price: 250 },
      { name: "Mango Shake", desc: "", price: 250 },
      { name: "Flax Seed Shake with Milk", desc: "", price: 250 },
      { name: "Chocolate Banana Shake", desc: "", price: 250 },
      { name: "Strawberry Shake", desc: "", price: 250 },
      { name: "Avocado Shake", desc: "", price: 250 },
      { name: "Banana with Mango Shake", desc: "", price: 250 },
      { name: "Banana with Strawberry Shake", desc: "", price: 250 },
      { name: "Hasset Special Shake", desc: "Banana, strawberry, mango, chocolate, milk, honey, oats", price: 300 },
      { name: "Sport Juice", desc: "Oats, banana, peanut butter, milk, honey, avocado", price: 270 },
    ],
  },
  colddrinks: {
    label: "Cold Drinks",
    icon: "snowflake",
    color: "#0284C7",
    items: [
      { name: "Lemon Head", desc: "", price: 200 },
      { name: "Ice Coffee", desc: "", price: 200 },
      { name: "Ice Tea", desc: "", price: 200 },
      { name: "Lemon Mojito", desc: "", price: 200 },
      { name: "Strawberry Mojito", desc: "", price: 250 },
      { name: "Watermelon Mojito", desc: "", price: 200 },
      { name: "Soft Drink", desc: "", price: 70 },
      { name: "Water (½ litre)", desc: "", price: 50 },
      { name: "Water (1 litre)", desc: "", price: 65 },
    ],
  },
  hotdrinks: {
    label: "Hot Drinks",
    icon: "coffee",
    color: "#78350F",
    items: [
      { name: "Tea", desc: "", price: 40 },
      { name: "Macciato", desc: "", price: 90 },
      { name: "Cappuccino", desc: "", price: 120 },
      { name: "Espresso", desc: "", price: 70 },
      { name: "Coffee", desc: "", price: 70 },
      { name: "Keshir", desc: "", price: 70 },
      { name: "Keshir with Honey", desc: "", price: 100 },
      { name: "Flavor Tea", desc: "", price: 90 },
      { name: "Fruit Tea", desc: "", price: 90 },
      { name: "Hot Chocolate", desc: "", price: 120 },
      { name: "Lemon Tea", desc: "", price: 70 },
      { name: "Fasting Machiato", desc: "", price: 110 },
      { name: "Milk", desc: "", price: 100 },
      { name: "Latte", desc: "", price: 120 },
      { name: "Special Tea with Alcohol", desc: "", price: 130 },
      { name: "Special Tea Non-Alcohol", desc: "", price: 115 },
      { name: "Ləwəz — Almond", desc: "", price: 100 },
      { name: "Ləwəz with Coffee", desc: "", price: 130 },
      { name: "Ye-jebena Coffee", desc: "", price: 60 },
    ],
  },
  alcohol: {
    label: "Alcohol",
    icon: "wine",
    color: "#7C3AED",
    items: [
      { name: "Beer", desc: "", price: 100 },
      { name: "Heineken", desc: "", price: 120 },
      { name: "Arada Beer", desc: "", price: 120 },
      { name: "Draft", desc: "", price: 60 },
      { name: "Awash Tekeshino", desc: "", price: 1200 },
      { name: "Awash Wine", desc: "", price: 800 },
      { name: "Guder Wine", desc: "", price: 800 },
      { name: "Axumawit Wine", desc: "", price: 900 },
      { name: "Gebeta Wine", desc: "", price: 1000 },
      { name: "Accia Wine", desc: "", price: 1500 },
      { name: "Kemila Wine", desc: "", price: 1200 },
      { name: "Habesha Areke (cc)", desc: "", price: 50 },
      { name: "Habesha Areke (litre)", desc: "", price: 800 },
    ],
  },
};

export const GROUPS = [
  { id: "food", label: "Food", cats: ["breakfast", "traditional", "pasta", "fish", "beef", "chicken", "burger", "pizza", "wrap", "salad", "soup"] },
  { id: "drinks", label: "Drinks", cats: ["juice", "colddrinks", "hotdrinks", "alcohol"] },
];
